<a href="https://colab.research.google.com/github/huynhhoc/ThuchanhToanCC/blob/main/Chuong5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sympy import sqrt, simplify, count_ops, oo

In [ ]:
import sys
sys.setrecursionlimit(30000)

#Phép lặp để tìm nghiệm

In [ ]:
x = 1.5
lap = 1
while x != sqrt(x +1):
  x = sqrt(x + 1)
  lap = lap +1

In [ ]:
x

1.61803398874989

#Sử dụng hàm solve trong sympy

In [ ]:
import sympy as sp 
from sympy import Symbol 
x = Symbol('x') 
sp.solve(x-sp.sqrt(1+x),x)

[1/2 + sqrt(5)/2]

#Vector

In [1]:
import numpy as np 
v1 = np.array([1., 2., 3.]) # tạo vector 3 chiều 
v2 = np.array([2., 1., 0.])

In [2]:
v3 = v1 + v2 # cộng vecto

In [3]:
v3

array([3., 3., 3.])

# Các phép toán trên vector:

* Ghép nối (hstack)

In [5]:
v4 = np.hstack([v1, v2])
v4

array([1., 2., 3., 2., 1., 0.])

* Phép nhân vô hướng

In [6]:
v5 = np.dot(v1, v2)
v5

4.0

In [8]:
 angles = np.linspace(0, np.pi/2, 5)
 angles

array([0.        , 0.39269908, 0.78539816, 1.17809725, 1.57079633])

In [9]:
np.sin(angles)

array([0.        , 0.38268343, 0.70710678, 0.92387953, 1.        ])

Lưu ý: Hàm sin trong gói sympy

In [10]:
import sympy as sy 
sy.sin(angles) 

AttributeError: ignored

In [11]:
from sympy import sin as sysin 
angles = np.linspace(0, np.pi/2, 5) 
sinangle = np.zeros(5) # tương đương >>> sinangle = np.array([0.0, 0.0, 0.0, 0.0, 0.0]) 
len(angles) # kiểm tra kích thước/số chiều của vector angles. 
for i in range(len(angles)): 
 sinangle[i] = sy.sin(angles[i]) # lưu ý: ở đây phải enter 2 lần để thoát khỏi vòng for. 

In [12]:
sinangle

array([0.        , 0.38268343, 0.70710678, 0.92387953, 1.        ])

# Thực hành 5: tính tổng tính giữa ma trận và vector

In [13]:
import numpy as np 
goc = np.pi/3 
A = np.array([ [np.cos(goc), -np.sin(goc)], 
 [np.sin(goc), np.cos(goc)] ])

In [14]:
A

array([[ 0.5      , -0.8660254],
       [ 0.8660254,  0.5      ]])

In [15]:
V = np.array([1. , 0. ]) 
Y = np.dot(A, V) 
Y

array([0.5      , 0.8660254])

Thực hành 6: hàm diff

In [19]:
from numpy import diff 
dx = 0.1 
y = [1, 2, 3, 4, 4, 6, 6] 

In [20]:
diff(y)

array([1, 1, 1, 0, 2, 0])

In [17]:
dy = diff(y)/dx
dy

array([10., 10., 10.,  0., 10., 10.])